### ISSUE TITLE
Create Wheels for 32bit Python on Windows

### ISSUE THREAD

**Issue by jgiers9872** [reloadware/reloadium#1]
I'm stuck in a 32bit Python environment (3.7), and would love to use Reloadium, but there are no wheels available for that architecture.  Upon installing the IntelliJ plugin, the 0.0.1 version of from pypi was installed for my environment, but this lacks the necessary imports and did not work.

**Comment by dkrystki** [comment]
Hi, thanks for submitting this.

Fixed in 0.7.17 and 0.7.1 (Pycharm plugin).
