### ISSUE TITLE
Limit files watched

### ISSUE THREAD

**Issue by iarp** [reloadware/reloadium#10]
Is there anyway to limit what is watched? It's watching even the `.git` directory.

**Comment by dkrystki** [comment]
That's strange. Dot files and dot directories are ignored by default.
On what os are you running it on?

**Comment by iarp** [comment]
I've come to realize two things. First, it's inotify logging about changes and second it happened when i left pycharm. I had just made a change and commited it, i didn't manually ctrl+s as I have pycharm auto saving. I think reloadium was notified of the file saving and reloaded at the same time i was commiting and then seeing the inotify logging files in .git directory made me think it was watching those files too.

> 2022-05-06 07:39:18.042 | DEBUG    | reloadium.vendored.watchdog.observers.inotify_buffer | reloadium.vendored.watchdog.observers.inotify_buffer:_group_events:57 - in-event <InotifyEvent: src_path=b'/home/iarp/Documents/Projects/iarp_site/.git/logs/HEAD', wd=134, mask=IN_CLOSE_WRITE, cookie=0, name=HEAD>

I think I can close this.
