### ISSUE TITLE
File change is recognized, but executed code stays as-is

### ISSUE THREAD

**Issue by MarijkeStein** [reloadware/reloadium#104]
[demo.txt](https://github.com/reloadware/reloadium/files/10720580/demo.txt)
## Describe the bug*

The attached `demo.py` provides just 2 Python functions. If executed under Reloadium, file-changes are noticed. However, the executed code seems unchanged.

## To Reproduce
1. Execute: `reloadium run demo.py` in a terminal (not PyCharm)
2. Open `demo.py` in some editor
3. In line 20-21 change the values of `x` and `y` to other values, and save the file
4. Note that Reloadium recognizes the file change:
  ```
  Update Module: __main__
  Update Function: mainLoop(13-27)
  ```
5. Observe that the console output `result = 6` does not change.

## Expected behavior
When changing the values of `x` and `y` to e.g. `3` and `5` it should print the output `result = 15`

## Screenshots
```
$ reloadium run demo.py 
■■■■■■■■■■■■■■■■
Reloadium 0.9.10
■■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a star at https://github.com/reloadware/reloadium
result = 6
result = 6

Loaded 1 watched modules so far from paths:
 - /hri/localdisk/mstein/code/ReloadiumDemo/**/*.py

result = 6
result = 6
result = 6
result = 6
Update Module: __main__
Update Function: mainLoop(13-27)

result = 6
result = 6
result = 6
result = 6
<CTRL+C>
```

## Desktop or remote (please complete the following information):**
 - OS: Ubuntu Linux 22.04 LTS
 - M1 chip: no
 - Reloadium package version: 0.9.10
 - PyCharm plugin version: None - not using PyCharm
 - Editor: Kate 19.12.3
 - Python Version: 3.9.16 from Anaconda 2022.10
 - Python Architecture: 64 bit
 - Run mode: Run

**Comment by MarijkeStein** [comment]
Here an even simpler example:
```
#!/usr/bin/env python3

import time

def mainLoop() -> None:
    running = True

    while running:
        try:
            time.sleep( 1 )

            result = 5 * 5
            print( f'result = {result}' )

        except KeyboardInterrupt:
            running = False


if __name__ == '__main__':
    mainLoop()
```

Changing the numbers in `result = 5 * 5` to sth. else is recognized, but the print value is always 25.

**Comment by dkrystki** [comment]
Duplicate https://github.com/reloadware/reloadium/issues/26 
The frame has to be suspended in debug mode to be reloaded.

**Comment by MarijkeStein** [comment]
Thanks for the quick reply! I didn't notice that the two tickets had the same root cause.
