### ISSUE TITLE
View in dark mode of Pycharm

### ISSUE THREAD

**Issue by mihalt** [reloadware/reloadium#110]
This is how I see it :)

![изображение](https://user-images.githubusercontent.com/30621622/219873735-d2318f03-9cfd-4731-a00c-972812e0da88.png)

![изображение](https://user-images.githubusercontent.com/30621622/219873718-42dd301f-3d3d-4f71-99c1-e61f902b710a.png)

**Comment by dkrystki** [comment]
Do you use any particular theme? 
I can't reproduce it using Darcula and high contrast.

**Comment by dkrystki** [comment]
I managed to reproduce it.
It happens when switching themes from light to dark.
It's not really a reloadium issue.

The way to fix it is restart PyCharm.
