### ISSUE TITLE
Reloadium crashes when using snoop

### ISSUE THREAD

**Issue by ChillarAnand** [reloadware/reloadium#112]
## Describe the bug*

When making changes to while loop and saving, reloadium crashes with `SIGBUS`. 

## To Reproduce

Script to reproduce the issue is available at https://github.com/ChillarAnand/avilpage.com/blob/master/scripts/confluent_kafka_consumer.py

Run the script with reloadium.
Add a new print statement in the while loop and save.

## Expected behavior
Reloadium shouldn't crash.

## Screenshots

<img width="1273" alt="Screenshot 2023-02-23 at 17 45 53" src="https://user-images.githubusercontent.com/4463796/220904317-44c1b712-41fa-4748-83c1-ae6a6238e64c.png">

## Desktop or remote (please complete the following information):**

OS: Mac
OS version: 13.0.1
M1 chip: yes
Reloadium package version: 0.9.10
PyCharm plugin version: 0.9.5
Editor: PyCharm
Python Version: 3.9.12
Python Architecture:64
Run mode: Debug

**Comment by dkrystki** [comment]
Fixed in reloadium 1.0.0 and PyCharm plugin 1.0.0
