### ISSUE TITLE
Can't start celery worker

### ISSUE THREAD

**Issue by alessio-b2c2** [reloadware/reloadium#117]
## Describe the bug*
When I try to debug with reloadiuma celery worker in pycharm, I get the following error:
```
■■■■■■■■■■■■■■■■
Reloadium 0.9.11
■■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a star at https://github.com/reloadware/reloadium
Usage: python -m celery worker [OPTIONS]
Try 'python -m celery worker --help' for help.

Error: No such option: --noreload
```

## To Reproduce
Create a run configuration in PyCharm for celery like this:
<img width="735" alt="Screenshot 2023-03-01 at 14 51 50" src="https://user-images.githubusercontent.com/84774195/222158424-b652339f-db19-429f-a570-a3bdd1d82483.png">

Deebug it with reloadium (clicking the orange debug button)

## Expected behavior
I expect to start the celery worker.

## Desktop or remote (please complete the following information):**
 - OS: macos 
 - OS version: 13.2.1
 - M1 chip: no
 - Reloadium package version: 0.9.11
 - PyCharm plugin version: 0.9.6
 - Editor: PyCharm 2022.3.2
 - Python Version: 3.10.9
 - Python Architecture: 64bit
 - Run mode: Debug

**Comment by dkrystki** [comment]
Fixed in reloadium 1.0.0 and PyCharm plugin 1.0.0
