### ISSUE TITLE
Not working with docker compose

### ISSUE THREAD

**Issue by thomas15v** [reloadware/reloadium#122]
## Describe the bug*

I get this error trying to run a python application

java.lang.NoSuchMethodException: com.pty4j.unix.UnixPtyProcess.addRemoteTunnel(int,java.lang.String,int)

## To Reproduce
1. Create a python application that runs in a docker container using docker-compose.yml
2. Add this docker-compose in pycharm as an interpreter
3. Create a python run configuration and set this docker-compose.yml application as interpreter
4. Click on run

## Screenshots
![image](https://user-images.githubusercontent.com/2163941/224289422-a4f12472-1b47-4b47-882f-e83e4c5a3319.png)
![image](https://user-images.githubusercontent.com/2163941/224289530-31682e73-0475-4c65-abb1-f92a4f6945b4.png)
![image](https://user-images.githubusercontent.com/2163941/224289639-0695f42a-1766-4772-98d4-66680424f534.png)

## Desktop or remote:
 - OS: Ubuntu 22.10 x86_64
 - M1 chip: no
 - Reloadium package version: 1.0.0
 - PyCharm plugin version: 1.0.0
 - Editor: PyCharm 2022.3.3
 - Python Version: 3.9.2
 - Python Architecture: 64Bit
 - Run mode: Run / debug and fast debug

**Comment by dkrystki** [comment]
Fixed in reloadium 1.0.1 and PyCharm plugin 1.0.1 but won't work until this one is fixed https://youtrack.jetbrains.com/issue/PY-53568/Targets-API-Path-mappings-field-is-missing-in-the-python-interpreter-settings
Remote interpreters need path mappings to work with reloadium.

**Comment by thomas15v** [comment]
Would it be possible to implement this fix in the legacy method? It can be enable by disabling python.use.targets.api in the Registry.

The feature does however work fine in the targets API. But sadly enough it is to unstable for use.

**Comment by dkrystki** [comment]
I've never heard of the legacy method. I'll check it out.

If they don't fix it in the next release I'll add path mappings settings to Reloadium settings to specify it there.

**Comment by antondeliverect** [comment]
@dkrystki really looking forward for that fix._.
