### ISSUE TITLE
Upgrade Reloadium to 1.0.0 doesn't update `reloadium_launcher` version, causing PyCharm to warn obsolete version

### ISSUE THREAD

**Issue by Jasonnor** [reloadware/reloadium#126]
## Describe the bug*
After Reloadium is upgraded to `1.0.0`, the `reloadium_launcher` version is still `0.9.5`, causing PyCharm to warn: 

```
This Reloadium version is obsolete.
Please update by running "pip install reloadium --upgrade"
```

## To Reproduce
1. Debug / Run Python with Reloadium in PyCharm
2. Got error `This Reloadium version is obsolete.`

```bash
/usr/local/bin/python3.7 -m reloadium_launcher pydev_proxy /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 65105 --file test.py 
Connected to pydev debugger (build 223.8836.43)
■■■■■■■■■■■■■■■
Reloadium 0.9.5
■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a star at https://github.com/reloadware/reloadium
This Reloadium version is obsolete.
Please update by running "pip install reloadium --upgrade"

Process finished with exit code 1
```

3. Run `pip install reloadium --upgrade` to upgrade Reloadium to `1.0.0`

```bash
> /usr/local/bin/python3.7 -m pip install reloadium --upgrade
Collecting reloadium
  Using cached reloadium-1.0.0-cp37-cp37m-macosx_10_9_x86_64.whl (3.1 MB)
Installing collected packages: reloadium
Successfully installed reloadium-1.0.0
> /usr/local/bin/python3.7 -m pip freeze | grep reloadium
reloadium==1.0.0
> /usr/local/bin/python3.7 -m pip list | grep reloadium
reloadium             1.0.0
```

4. Debug / Run Python with Reloadium in PyCharm again
5. Same error still occurred

## Expected behavior
Debug / Run without error.

## Screenshots
![image](https://user-images.githubusercontent.com/7609173/226819746-b97dc2d4-4b7f-4a10-bfac-3766dea1b314.png)
![image](https://user-images.githubusercontent.com/7609173/226819991-8d56993f-f013-44d0-a733-298046327284.png)

## Desktop or remote (please complete the following information):**
 - OS: macOS
 - OS version: Ventura 13.2
 - M1 chip: yes
 - Reloadium package version: 1.0.0
 - PyCharm plugin version: 1.0.0
 - Editor: PyCharm
 - Python Version: 3.7.9
 - Python Architecture: 64bit
 - Run mode: Run & Debug

## Additional context
- Have checked Reloadium version with:
```bash
> /usr/local/bin/python3.7 -m reloadium_launcher -h
INFO
  version      0.9.5

COMMANDS
  help/-h      Shows this help
  run          Runs a python file. Add -m to run a module.

> /usr/local/bin/python3.7 -m reloadium -h
INFO
  version      1.0.0

COMMANDS
  help/-h      Shows this help
  run          Runs a python file. Add -m to run a module.
```
- Tried to reinstall Reloadium, the error still occurs
- My environment does not have other versions of Python installed, so the interpreter has only one setting

Please let me know if any additional information is required. Thank you!

**Comment by dkrystki** [comment]
Fixed in reloadium 1.0.1 and PyCharm plugin 1.0.1

**Comment by dkrystki** [comment]
@Jasonnor You may need to upgrade your PyCharm version to the newest one to install that version.

**Comment by Jasonnor** [comment]
@dkrystki No issues after upgrading to `1.0.1`. Thanks for your help!
