### ISSUE TITLE
Unmatched ".

### ISSUE THREAD

**Issue by philastrophist** [reloadware/reloadium#129]
## Describe the bug*

Run debug reloadium from pycharm in a remote environment. Get:

```
ssh://<>@<>:22/home/<>/miniconda2/envs/<>/bin/python -m reloadium pydev_proxy -u /home/<>/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 33861 --file /tmp/pycharm_project_5/folder/file.py
Unmatched ".
```
## To Reproduce
1. Click reloadium debug

## Expected behavior
It runs

## Desktop or remote (please complete the following information):**
 - OS: Ubuntu 
 - OS version: 20.04.1
 - Reloadium package version: 1.0.1
 - PyCharm plugin version: 0.9.5
 - Editor: PyCharm
 - Python Version: 3.7
 - Python Architecture: 64
 - Run mode: Debug or run doesn't matter

Not much else to say here

**Comment by dkrystki** [comment]
Could you upgrade your plugin to the newest one (1.0.1) and try again?

**Comment by dkrystki** [comment]
Closing due inactivity.
