### ISSUE TITLE
Multi-threading fails from 0.9.5

### ISSUE THREAD

**Issue by laurapons** [reloadware/reloadium#132]
Multithreading does not work on PyCharm from version 0.9.5 (so last working version is 0.9.5, which launches reloadium 0.9.10), which forces to work on PyCharm 2022.2.5). It works great on 0.9.5, but the versions after this one break the multi-threading. 

I can't provide a working example, because I cannot share my code. I'll try to create a sample after the peak of work.
For now I still work with 0.9.5, which forces me to have **PyCharm 2022.2.**

PyCharm 2022.2.5 (Community Edition)
Build #PC-222.4554.11, built on March 15, 2023
Runtime version: 17.0.6+7-b469.82 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2010M
Cores: 8
Non-Bundled Plugins:
    com.microsoft.vso.idea (1.162.1)
    org.reloadium (0.9.5)

## Desktop or remote (please complete the following information):**
 - OS: W11
 - PyCharm plugin version: 0.9.5 and so on
 - Editor: PyCharm
 - Python Version: 3.8.1
 - Python Architecture: 64bit
 - Run mode: all modes (Run/Debug/Fast Debug)

**Comment by dkrystki** [comment]
Is it multiprocessing or multithreading not working? 
I tried both and it seems to be ok.

In what way it's not working for you? Is there an error?

**Comment by laurapons** [comment]
I just tried 1.1.0 with PyCharm Community 2023.1 and it all works as expected. Closing the bug (apologies by the late reply).
