### ISSUE TITLE
Does it support hot reloading of third-party libraries when using pycharm+pytest?

### ISSUE THREAD

**Issue by god-chaos** [reloadware/reloadium#134]
The reloadable paths is configured on the reloadium pycharm plugin. 

When pytest is used to execute a testcase and a third-party library file is modified, but hot reloading cannot be performed. The following information is displayed:

```shell
xxx has been modified but is not loaded yet
Hot reloading not needed.
```

**Comment by dkrystki** [comment]
That message means the file hasn't been imported when the file was modified.
Only loaded (imported by the interpreter) modules can be hot reloaded.
To make sure the module is loaded add a `print` function to see if the module is executed prior to hot reloading
