### ISSUE TITLE
`RecursionError: maximum recursion depth exceeded while calling a Python object`

### ISSUE THREAD

**Issue by antondeliverect** [reloadware/reloadium#141]
## Describe the bug
I believe this error happens when I'm running reloadium on a very large project. 
I.e. despite the fact, that I've specified to 'watch only 1 file'(just trying to test things out), it still seems to load the whole thing(all .py files out there). 

## To Reproduce
1. Go to 'Settings -> Reloadium project settings'
2. Specify single file in 'reloadable paths'
3. Start project with a lot of files(there's thousands of files i believe), see error

## Expected behavior
Project runs. 

## Screenshots
![my](https://user-images.githubusercontent.com/103994541/234315793-d0a931cc-69ab-4152-a0c5-b881a2384c49.png)

error finishes with 

```
File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
state = deepcopy(state, memo)
File "/usr/local/lib/python3.10/copy.py", line 137, in deepcopy
     d = id(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
Reloadium experienced a fatal error and has to quit.
Please submit a github issue to let us know at https://github.com/reloadware/reloadium
```

## Desktop or remote (please complete the following information):**
 - OS: [MacOS]
 - OS version: [12.6 (21G115)]
 - M1 chip: [yes]
 - Reloadium package version: [1.1.0]
 - PyCharm plugin version: [1.1.0]
 - Editor: [PyCharm]
 - Python Version: [3.10.9]
 - Python Architecture: [64bit]
 - Run mode: [Debug]

## Additional context

I verified that it happens specifically due to large amount of loaded files by adding whole project in ignore paths and specifying in 'reloadable paths' only a single file. 
<img width="903" alt="Screenshot 2023-04-25 at 16 47 34" src="https://user-images.githubusercontent.com/103994541/234315843-76139569-0a9e-4d6c-a652-3d00ebf41295.png">

Despite the fact that it didn't worked as I expected(there were 0 files loaded instead of single file), I still could see that project started in debug mode: 

![Untitled](https://user-images.githubusercontent.com/103994541/234316225-5f229d8e-593c-413c-a058-fb13259e37b1.png)

**Comment by dkrystki** [comment]
I believe this is happening because `Add current working directory to reloadable paths` is selected.
Could you unselect that, add only files of interest to reloadable paths and try again?

**Comment by antondeliverect** [comment]
@dkrystki you're right, it helped! thank you
