### ISSUE TITLE
Version Unsupported Error

### ISSUE THREAD

**Issue by infiniteYuanyl** [reloadware/reloadium#142]
## Describe the bug

My mac is M1 and my python is 3.9.When I debug a deeplearning program with pytorch2.0,it currupted and told me the version was not supported, but it was actually not.
## Screenshots
<img width="777" alt="image" src="https://user-images.githubusercontent.com/96183490/234535831-7d356fd2-8b4f-404d-ae0b-1b55aa244b2a.png">

## Desktop or remote (please complete the following information):**
 - OS: MacOs
 - OS version: 13.3
 - M1 chip: yes
 - Reloadium package version: None
 - PyCharm plugin version: 0.9.5
 - Editor: Pycharm
 - Python Version: 3.9
 - Python Architecture: 64bit
 - Run mode: Debug

**Comment by dkrystki** [comment]
This issue has already been fixed. 
Please upgrade to the newest plugin version (1.1.0). 
Note that you may need to upgrade your PyCharm version to install this version
