### ISSUE TITLE
why automatically jumps to some breakpoint far away from X

### ISSUE THREAD

**Issue by sajsxj** [reloadware/reloadium#149]
In debug, when I add a comment on line x, and there is a breakpoint above and below line x, after saving, the program automatically jumps to some breakpoint far away from X. I would like to know how to solve it, thank you very much

**Comment by dkrystki** [comment]
Hi @sajsxj 
Could you provide more details? I can't reproduce it.
Which version of the plugin are you using?
Does it always happen or only sometimes?

**Comment by dkrystki** [comment]
Also is the breakpoint it jumps to in the same function or a different one?

**Comment by sajsxj** [comment]
@dkrystki Ok, let me redescribe the problem I encountered, and the rest of the description is in the debug case.

I have attached some pictures below. When the program reaches the last breakpoint, modify the comment two. After the hot load file is executed, the program will automatically jump to the first breakpoint
So how do you get it to jump to the point closest to comment two

Also, I would like to know if there is an option to set up a hot reload file manually or automatically

thanks！！！
<img width="265" alt="image" src="https://github.com/reloadware/reloadium/assets/56745682/8748a870-cd34-46df-951e-299c84c3dc75">
<img width="247" alt="image" src="https://github.com/reloadware/reloadium/assets/56745682/fc67036e-63a8-49a2-a8ff-218d5944b268">

**Comment by sajsxj** [comment]
Sorry, I forgot to tell you the version, reloadium1.1.1
emmm, maybe it is my improper use. I just started using it yesterday, and I hope you can give me some help

**Comment by sajsxj** [comment]
The jump also goes to the current function

**Comment by dkrystki** [comment]
Oh I see. It's not really a bug.
When debugging a function Reloadium restarts the whole body of the function on a change.
That is why your first breakpoint is hit.
Back in the days Reloadium would disable breakpoints before the current one to prevent that. 
I removed that behavior since it can be beneficial to step through a function once the code is changed.

**Comment by sajsxj** [comment]
ok, I see! Thank you very very very much！！！！

**Comment by dkrystki** [comment]
You're welcome!
