### ISSUE TITLE
not supported

### ISSUE THREAD

**Issue by Rinshark** [reloadware/reloadium#154]
Debugger goes like：
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.11 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run Reloadium with environmental variable RW_DEBUG=True

but  my pycharm version is 2020 of which it doesn't mentioned. The Pyhton version I found on the console is Python 3.9.4, which meets the requirements mentioned. So there is no reason that i can't use the Reloadium plugin......

**Comment by dkrystki** [comment]
Please update your plugin version to the newest.
You will need to update your PyCharm too because your version is not supported anymore.
