### ISSUE TITLE
only can't run in reloadium

### ISSUE THREAD

**Issue by jialay** [reloadware/reloadium#155]
when the class "CollinearMagneticStructureAnalyzer" from "pymatgen.analysis.magnetism.analyzer" is used, the reloadium failed to run or debug. The code is ok in original debug mode. 
I find that the 'struc' object is changed to a generator, which should not be.

**Comment by dkrystki** [comment]
Could you provide the source code of the class or a reproducer?
Also could you paste the error message ( you may need to run it with "RW_DEBUG" environmental variable set to `True` )?

**Comment by jialay** [comment]
the following code reproduce the error, it runs well, but only can't debug in reloadium,  and just output the error code ：“AttributeError: 'generator' object has no attribute 'copy' ”.

"
#to run the code, module pymatgen should be installed.
from pymatgen.core import Structure
from pymatgen.analysis.magnetism.analyzer import CollinearMagneticStructureAnalyzer
struct_a = Structure([[3, 0, 0], [0, 3, 0], [0, 0, 3]], ['Cr'], [[0, 0, 0]])
struct_b = Structure([[3, 0, 0], [0, 3, 0], [0, 0, 3]], ['Cr'], [[0, 0.5, 0.5]])
dup_ck = CollinearMagneticStructureAnalyzer(struct_a, overwrite_magmom_mode="none")
if dup_ck.matches_ordering2(struct_b):
    print('same structure')
"

**Comment by jialay** [comment]
> Could you provide the source code of the class or a reproducer? Also could you paste the error message ( you may need to run it with "RW_DEBUG" environmental variable set to `True` )?

the following code reproduce the error, it runs well, but only can't debug in reloadium,  and just output the error code ：“AttributeError: 'generator' object has no attribute 'copy' ”.

"
#to run the code, module pymatgen should be installed.
from pymatgen.core import Structure
from pymatgen.analysis.magnetism.analyzer import CollinearMagneticStructureAnalyzer
struct_a = Structure([[3, 0, 0], [0, 3, 0], [0, 0, 3]], ['Cr'], [[0, 0, 0]])
struct_b = Structure([[3, 0, 0], [0, 3, 0], [0, 0, 3]], ['Cr'], [[0, 0.5, 0.5]])
dup_ck = CollinearMagneticStructureAnalyzer(struct_a, overwrite_magmom_mode="none")
if dup_ck.matches_ordering2(struct_b):
    print('same structure')
"

**Comment by dkrystki** [comment]
I was unable to reproduce this.

![2023-08-01_12:53:15](https://github.com/reloadware/reloadium/assets/45499236/48d5c9a3-00fe-47e7-9449-ad505e1dff85)

Run on:
Reloadium version: 1.2.0
Python version: 3.10.8
pymagnet version: 2023.7.20
Os: Linux q 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dkrystki** [comment]
I managed to reproduce and fix this in Reloadium 1.2.1 and PyCharm plugin 1.2.1
