### ISSUE TITLE
Can't update pycharm plugin to latest version

### ISSUE THREAD

**Issue by chrisbeardy** [reloadware/reloadium#159]
## Describe the bug*
It appears I am stuck on version 0.9.10 of reloadium on the pycharm plugin. every time i run it it shows me this:

![image](https://github.com/reloadware/reloadium/assets/20585410/030da535-b794-4ab7-bba8-1153ca10457a)

however there is no option to upgrade in plugins:

![image](https://github.com/reloadware/reloadium/assets/20585410/c8eba963-9c1a-434a-b12a-f748fa23612a)

![image](https://github.com/reloadware/reloadium/assets/20585410/87f32d6a-07c0-4f2e-8fae-10dd3ba87836)

I have tried uninstalling and reinstalling, and upgrading pycharm to latest version.

## Desktop or remote (please complete the following information):**
 - OS: Windows 10
 - Reloadium package version: 0.9.10
 - PyCharm plugin version: 0.9.5 ?
 - Editor: pycharm
 - Python Version: 3.9
 - Run mode: both

**Comment by dkrystki** [comment]
@chrisbeardy You have to upgrade you pycharm version to download the newest Reloadium plugin.
