### ISSUE TITLE
Fast debug does not stop on breakpoints.

### ISSUE THREAD

**Issue by andyp05** [reloadware/reloadium#165]
## Describe the bug*
Fast debug does not stop on breakpoints. Regular reloadium debug and regular python debugger does work as expected.

## To Reproduce
1. Start debugger with Fast Debug with Reloadium.
2. Set a breakpoint in the code. I am running django.
3. Debugger does not stop on breakpoint.

## Expected behavior
Stop execution.

## Desktop or remote (please complete the following information):**
 - OS: Windows
 - OS version: 11
 - M1 chip: no
 - PyCharm plugin version: 1.2.1
 - Python Version: 3.10.4
 - Python Architecture: 64bit
 - Run mode: Debug

**Comment by dkrystki** [comment]
@andyp05 
What's the location of the breakpoint? Is it in module scope?

**Comment by andyp05** [comment]
Using django. User clicks a button which calls a view.
The view calls a function in another module.
Set a breakpoint in the other module.

Python debugger: works
Reloadium debugger: works
Reloadium Fast debugger: does not break on breakpoint.

**Comment by dkrystki** [comment]
Reloadium 1.3.2 and PyCharm plugin 1.3.2 add a lot of improvements to the Fast Debug mode. It should be working now.
