### ISSUE TITLE
not support WSL

### ISSUE THREAD

**Issue by mapengsen** [reloadware/reloadium#166]
when i use wsl conda env to run python file, then will get error , we hope can fix it soon.

**Comment by mapengsen** [comment]
Error running aaa
java.lang.NoSuchMethodException: ava.lang.Processlmpl.addRemoteTunnel(int java.lang.Strinq,int

**Comment by dkrystki** [comment]
Hi @mapengsen , I'll need more info to reproduce this. Please fill out the issue template.

**Comment by dkrystki** [comment]
Closing due inactivity.
