### ISSUE TITLE
Not support numba

### ISSUE THREAD

**Issue by papari1123** [reloadware/reloadium#167]
## Describe the bug*
When I run Reloadium in debug mode with Numba's njit mode, an UnsupportedError occurs.
If I run Reloadium in either the running mode or normal debugging mode, no exceptions occur.

## To Reproduce
first, install numba
```
pip install numba
```
copy code below, and just run reloadium in debug mode.
```
from numba import njit

@njit(cache=False)
def njit_test(tt):
    print(tt)

njit_test('hello')
```

## Expected behavior
no exceptions occur even during reloadium debugging mode with njit.

## Screenshots
![image](https://github.com/reloadware/reloadium/assets/33012030/4c99c970-1d45-419a-9a2b-36824d6dc65a)

## Desktop or remote (please complete the following information):**
 - OS: Linux Ubuntu
 - OS version: 22.04.02 LTS
 - M1 chip: no
 - Reloadium package version: 1.2.1
 - PyCharm plugin version:
![image](https://github.com/reloadware/reloadium/assets/33012030/8a374338-4128-415a-8136-d4d96d2145b4)

 - IDE : PyCharm
 - Python Version: 3.9.0
 - Run mode: reloadium debug

**Comment by dkrystki** [comment]
Added in Reloadium 1.3.2 and PyCharm plugin 1.3.2
