### ISSUE TITLE
No files are watched.

### ISSUE THREAD

**Issue by GaoSimon** [reloadware/reloadium#17]
**Describe the bug**
When I try to debug the python file, I get an error and can not hot reload the file.  It tells me that I do not watch this file. The details could be found in the picture.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44992796/170597461-8b6c2d5c-f3ab-4686-bd2e-7d786dceb34d.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS version: [22]
 - Reloadium package version: [0.8.8]
 - PyCharm plugin version: [ 0.8.2 ]
 - Editor: [PyCharm]
 - Run mode: [Debug]

**Additional context**

**Comment by GaoSimon** [comment]
How can I start the hot reloading?

**Comment by dkrystki** [comment]
@GaoSimon it seems like the dots in the path are causing this issue. 
Could you try running it in a directory without dots?

**Comment by GaoSimon** [comment]
@dkrystki yes,it works.Thank you!

**Comment by dkrystki** [comment]
Fixed in Reloadium [0.9.0]
