### ISSUE TITLE
Reloadimun not reloading modified pyhton files

### ISSUE THREAD

**Issue by Walid-Azur** [reloadware/reloadium#176]
## Describe the bug*
On PyCharm 2023.3 (Professional Edition), reloadimum 1.3.3 and 1.3.2
All watched files are listed.
When updating a python file I get this message :
 file.py has been modified but is not loaded yet.
Hot reloading not needed.

## To Reproduce
configure you watch paths, run your server (odoo), change a python file, 

## Expected behavior
It used to work and update the runtime

## Desktop or remote (please complete the following information):**
 - OS: Macos M1 Pro
 - OS version: 14.2
 - M1 chip: yes
 - Reloadium package version: 1.3.3
 - PyCharm plugin version: 2023.3 EAP
 - Editor: Pycharm
 - Python Version: 3.11 and 3.10
 - Python Architecture: 64
 - Run mode: Run

## Additional context
Nan

**Comment by jEeVaf** [comment]
1,"reloadimum" plugin (both 1.3.3 and 1.3.2) are compatible with PyCharm 2023.3 Professional Edition. Sometimes, plugin updates may be required to match the IDE version.
2. settings for the "reloadimum" plugin. There might be an option or setting that needs adjustment. Look for any configuration related to file watching and hot reloading.
3.  file you are trying to modify is properly recognized by PyCharm. Check if the file is part of the project and is not excluded from the source.
4.  file you are trying to modify is properly recognized by PyCharm. Check if the file is part of the project and is not excluded from the source.

**Comment by dkrystki** [comment]
@Walid-Azur Can you check if it's still reproducible in version 1.4.0?

**Comment by dkrystki** [comment]
Closing due inactivity.
