### ISSUE TITLE
VSCode plugin roadmap

### ISSUE THREAD

**Issue by Mirac-Le** [reloadware/reloadium#179]
Dear Reloadium project maintainers,
I am captivated by the features of Reloadium as presented on your official website. Unfortunately, I use VSCode as my primary production tool, rather than PyCharm. Thus, I would like to inquire whether you could provide a more detailed roadmap for this project. Thank you!

**Comment by dkrystki** [comment]
Hi @Mirac-Le 
VsCode plugin is definitely coming but it's difficult to give a timeline on it. 
Having a full time job and still quite a lot of work on PyCharm plugin an initial version of VsCode plugin might be still a couple of months away.
