### ISSUE TITLE
Reloadium profiler not displayed

### ISSUE THREAD

**Issue by laurapons** [reloadware/reloadium#180]
## Describe the bug*
I've never been able to use the profiler. I am working with a team where we all have the same computer, same PyCharm version, same venv - we use poetry to get the exact same versions-, and only 1 member (from 5 people) can see the time profiling (not sure about the memory profiling).

I tested the new ui and the old ui, the theme in which he made it work, but I cannot see any profile, not even on the simplest test.

## To Reproduce
I installed the plugin from the File>Settings>Plugins and from the Python Packages tab (they are both 1.3.4).
Here are the details and a small video.
https://github.com/reloadware/reloadium/assets/1275184/6be1821c-94f6-4f00-beae-445d30aee2d2

When I trigger the reloadium debugger, it prompts with this warning:
`warning: PYDEVD_USE_CYTHON environment variable is set to 'NO'. Frame evaluator will be also disabled because it requires Cython extensions to be enabled in order to operate correctly.`
What is strange is that the person the made it work with the exact same computer, same configuration, also has this warning and can see the line profiler

PyCharm 2023.3.3 (Professional Edition)
Build #PY-233.13763.11, built on January 25, 2024
Licensed to Lunaphore Technologies SA / Laura Pons Lloret
You have a perpetual fallback license for this version.
Subscription is active until January 22, 2025.
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 28
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.gmike.visual-studio-2019-dark (1.5.3)
  com.microsoft.vso.idea (1.162.2)
  org.sonarlint.idea (10.3.0.77475)
  org.reloadium (1.3.4)

## Desktop or remote (please complete the following information):**
Windows 11
13th Gen Intel(R) Core(TM) i7-13850HX   2.10 GHz

 - Reloadium package version: 1.3.4
 - PyCharm plugin version: 1.3.4
 - Editor: PyCharm 2023.3.3 (Professional Edition)
 - Python Version: 3.8.10
 - Run mode: Debug

**Comment by dkrystki** [comment]
From the video I can see that Reloadium Free is used. Time profiling is only available in Reloadium Pro.
