### ISSUE TITLE
async functions not reloading

### ISSUE THREAD

**Issue by Cleroth** [reloadware/reloadium#24]
Plugin seems to ignore functions marked `async`. Are they not meant to be reloadable?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Reloadium package version: 0.9.0
 - PyCharm plugin version: 0.8.3
 - Editor: PyCharm 2022.1.3 (Pro Edition)
 - Run mode: Both

**Comment by Cleroth** [comment]
Off-topic: Consider lowering the sponsorship minimum to $5. $10 is IMO too much and likely why you don't have any sponsors yet.

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.1
