### ISSUE TITLE
Reloadium randomly breaks itself on PyCharm Manjaro

### ISSUE THREAD

**Issue by hlafaille** [reloadware/reloadium#25]
**Describe the bug**
Reloadium nuked itself and now throws a stack trace whenever launching PyCharm. 

**To Reproduce**
1. Launch IDE
2. Reloadium Fails to load. Worked earlier on this exact system.

**Expected behavior**
Reloadium to work.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - OS version: 21.3.1 Ruah
 - Reloadium package version: Can't tell, Reloadium doesn't work.
 - PyCharm plugin version: 0.8.3
 - Editor: PyCharm
 - Run mode: No Reloadium Option

**Additional context**
https://pastebin.com/aDtdGsXw

**Comment by dkrystki** [comment]
Interesting. 
Not sure if it's the plugin's or PyCharm's fault .
Have your tried uninstalling and installing the plugin again?

**Comment by hlafaille** [comment]
Yeah. Latest version of PyCharm too. I am running the [Arch User Repository version](https://archlinux.org/packages/community/x86_64/pycharm-community-edition/).
