### ISSUE TITLE
Add all python files in multiple nesting directories

### ISSUE THREAD

**Issue by adoxentor** [reloadware/reloadium#32]
Loaded 0 watched modules so far from paths:
projects/

there are at least 3 directories between projects/ and my python files.
It works when I add each module directory to the re-loadable paths.
maybe the issue is that there are over 800 python files in the folder?

**Comment by dkrystki** [comment]
Interesting, that definitely should be working. 
What OS and python versions are you running it on?
Number of files shouldn't matter unless there are some watchdog limits I'm not aware of.

**Comment by adoxentor** [comment]
ubuntou 18.04 and the files are in a mounted network drive with slow events ("PyCharm cannot receive filesystem event notifications for the project" error also happens but watchdog does work.)
If hooking into the IDE's save is an option it will probably be the only sure solution for this use case, which is common in bigger projects.

Big change suggestion:
A manual mode that will trigger reload on the current file \ selected directory in the project view\ (only selected context?). 
It might be instead of hooking the IDE's save method. 
Be default using disk change date to check if files changed since last reload.

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.3 and PyCharm plugin 0.8.6
Also added the manual reload button.
