### ISSUE TITLE
[Feature Request] Pop an extra frame

### ISSUE THREAD

**Issue by adoxentor** [reloadware/reloadium#38]
It will be useful if there was a way to pop additional frames after reloading, for example when changing the current function's signature, or when a break-point is inside a loop.
And sense you already implemented frame restart, maybe add it as a button so when debugging we could trigger it without adding "pass" to the start of the function.

**Comment by dkrystki** [comment]
By pop you mean drop frame (remove from the call stack)?

About the manual frame restart - that's a good idea, I'll try to add in the next release.

**Comment by dkrystki** [comment]
Added in reloadium 0.9.7 and PyCharm plugin 0.9.2
