### ISSUE TITLE
Reloadium fails to start: Too many open files

### ISSUE THREAD

**Issue by wgordon17** [reloadware/reloadium#41]
**Describe the bug**
When using the Reloadium plugin for PyCharm with the `runserver` command (both `run` and `debug` from the plugin fail), PyCharm hangs for a while and then fails on "Too many open files".

**To Reproduce**
1. Start with an baseline Django project (I used PyCharm's built-in "New Project" > "Django" for testing the reproducer)
2. Add a `package.json` file to define a whole bunch of NodeJS dependencies (here's a sample one that I was able to get this to recreate with: https://gist.github.com/wgordon17/3d3f6bbffc69addc690a6e984e043c3a)
3. Run `npm installl`, which creates a local `node_modules` directory
4. Add `node_modules` to the exclusion list 
![image](https://user-images.githubusercontent.com/22222756/189664072-265badab-b65a-4a1a-a144-18649af6d9f4.png)
5. Attempt to Run/Debug the Django `runserver` with Reloadium

**Expected behavior**
Reloadium should run as expected

**Desktop (please complete the following information):**
 - OS: MacOS Monteray
 - OS version: 12.5
 - Reloadium package version: 0.9.2
 - PyCharm plugin version: 0.8.5
 - Editor: PyCharm 2022.2.1 Professional
 - Run mode: This happens regardless of run mode

**Additional context**
Having a `node_modules` directory and running NodeJS packages alongside Django is a common pattern. Since Reloadium focuses on Python, it would probably make sense to include a hard coded `node_modules` exclusion somewhere.

Although, I also suspect this problem isn't limited to just `node_modules`, I would expect the exclusion configuration to prevent `dirsnapshot.py` from doing whatever it's doing (the error code mentioned errors on line 283 in walk, so that's why I'm _guessing_ that's where this occurs). That way, this could prevent other issues similar to this.

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.3 and PyCharm plugin 0.8.6
