### ISSUE TITLE
Multiple issues with Reloadium 0.9.3

### ISSUE THREAD

**Issue by jacobm-tech** [reloadware/reloadium#47]
1. Debug with Reloadium does not work after upgrading to 0.9.3. It results in the following trace:
```
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\.reloadium\package\3.9\reloadium\__main__.py", line 5, in <module>
    start(sys.argv)
  File "C:\Users\user\.reloadium\package\3.9\reloadium\corium\l1l1llll1llll1l1Il1l1.py", line 627, in start
  File "C:\Users\user\.reloadium\package\3.9\reloadium\corium\l1l1llll1llll1l1Il1l1.py", line 102, in l1l1ll1ll1lllll1Il1l1
  File "C:\Users\user\.reloadium\package\3.9\reloadium\corium\l1l1llll1llll1l1Il1l1.py", line 81, in l11l111l11ll11llIl1l1
  File "C:\Users\user\Anaconda3\lib\pathlib.py", line 1285, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "C:\Users\user\Anaconda3\lib\pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "C:\Users\user\Anaconda3\lib\pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\JetBrains\\PyCharm 2022.2.2\\plugins\\python\\helpers\\pydev\\_pydevd_frame_eval\\pydevd_frame_eval_main.py.tmp'
```
I think I found a workaround: running PyCharm as administrator allows debugging with Reloadium to work, and then it works even if running normally when restarted subsequently. 

2. Files and modules in the project are decorated with orange squares when running or debugging with Reloadium. I assume this is to indicate that these files are being watched for changes. However, these squares do not go away even after the program is stopped. Don't know if it's intentional, but all these orange marks are a bit intense, and they become quite distracting when they are permanent. I would suggest making these marks optional in preferences.

3. After working with Reloadium run or debug, attempting to close PyCharm results in a "Background Tasks are Running" dialog. No background tasks are indicated in the task list. 

**To Reproduce**
Behavior occurs immediately when trying to debug after upgrading the PyCharm plugin to 0.8.6 with Reloadium 0.9.3.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS version: 11
 - Reloadium package version: [e.g 0.8.6]
 - PyCharm plugin version: 0.9.3
 - Editor: PyCharm
 - Run mode: Debug and Run

**Comment by dkrystki** [comment]
Hi @jacobm-tech big thanks for submitting this issue. 
I did test this version on windows prior to releasing and the error did not happen for me. 
It should be easy to fix though seeing the traceback.

About the squares. The idea was to indicate which files are reloadable.
Would making the squares smaller and go away after stopping the process help?
Also a good idea with the disable option.

I could not reproduce the "Background Tasks are Running". 
Could you confirm it is reproducible on your side?

I have removed the version from the marketplace until I release a hotfix.

**Comment by jacobm-tech** [comment]
Hi @dkrystki, thanks for making this plugin - I think it's great! 

I am no longer sure that the backround tasks thing is connected to Reloadium. I kept seeing it with Reloadium while trying to diagnose the issue above, because I was opening and closing it all the time. But I think it may just be PyCharm doing stuff silently when it is opened and closed frequently. If you know a way to see what PyCharm is doing in the background (with nothing in the task list), please let me know, and I'll see if there is something Reloadium-related in there.

The orange squares are a UI issue, I can't say that my own preference is the right one. I would definitely like them to go away when not running, and would also like them to be smaller or optional.  Also, I am not sure how useful they are: all Python files in the current project are reloadable, so they all get this decoration. It would be better to prominently indicate when something can't be reloaded, e.g. if you are debugging a Python file, you would get a message in the console, "Reloadium can't reload this file while running because $reason", if there is such a thing. 

Incidentally, the marks don't get applied consistently in my project, some files do not get them initially, but get them when you stop in the file, and reloading works fine.

**Comment by dkrystki** [comment]
@jacobm-tech appreciate the feedback!

Not sure about the background tasks issue. If it happens again I guess the best way to find out would be to look into idea.log file.

That's true that files in the current directory are watched by default (it can be turned off in the settings).
Some people though run Reloadium on projects with very complex directory structures adding external libraries to watched paths or ignoring others making the situation a bit tricky.

Indication does not mean only that the file is watched but also that is loaded by python interpreter (most likely the consistency thing you mentioned). That should help with situations where the user changes a file which is not imported and there is no effect (no update indications etc) which can be confusing.

I'll try making it a bit less intrusive and also add the disable checkbox. 
I think it is a useful feature but I'm open for further feedback and suggestions

**Comment by dkrystki** [comment]
@jacobm-tech Fixed version has been released. It's under the same number so you might need to uninstall and install again.
