### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by InterestingDarkness** [reloadware/reloadium#54]
**Describe the bug**
Not working on Python 3.11

**To Reproduce**
1. Install Python 3.11
2. Run Reloadium
3. It prints

> It seems like your platform or Python version are not supported yet.
> Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.
> Please submit a github issue if you believe Reloadium should be working on your system at
> https://github.com/reloadware/reloadium

**Expected behavior**
Working

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - OS version: 11
 - Reloadium package version: 0.9.4
 - PyCharm plugin version: 0.8.8
 - Editor: PyCharm
 - Run mode: Run and Debug

**Additional context**

**Comment by dkrystki** [comment]
Blocked by https://github.com/Nuitka/Nuitka/issues/1856

**Comment by augcampos** [comment]
O confirm this on virtual environments too.

**Comment by tj-pipesearch** [comment]
Get the same problem with pycharm 2022.3.2 as well as 2022.3
reloadium 0.9.5

**Comment by dkrystki** [comment]
Added in reloadium 1.0.1 and PyCharm plugin 1.0.1

**Comment by boxed** [comment]
This isn't blocked by the linked issue anymore?

**Comment by dkrystki** [comment]
@boxed they released a version that supports 3.11 except some speed improvements which is good enough for Reloadium purposes.

**Comment by kusrohit** [comment]
Is there any solution for this?

**Comment by dkrystki** [comment]
@kusrohit Python 3.11 is supported in the latest version.
