### ISSUE TITLE
Reloadium exit instantly and Variable inspections are not shown.

### ISSUE THREAD

**Issue by nagataaaas** [reloadware/reloadium#55]
**Describe the bug**
1. When I click orange debug button, reloadium process exits instantly.
2. In the official [Futures Page](https://reloadium.io/features/general-python), it says Reloadium shows variable inspection on the right of assignment. But nothing is shown after I cilck run button or debug button. 

**To Reproduce**
1. Install Reloadium from the PyCharm plugin store.
3. Write your code.
4. Click orange debug button or run button.
5. step4 opens console and it says process is exited.

**Expected behavior**
Show variable inspection on the right of variable.

**Screenshots**
![image](https://user-images.githubusercontent.com/32694778/198878700-6e36d0d7-e9cc-4c68-bcc5-aabccf9ae4fc.png)
In the console
```
connected to pydev debugger (build 222.4345.23)
■■■■■■■■■■■■■■■
Reloadium 0.9.4
■■■■■■■■■■■■■■■
If you like this project consider becoming a sponsor or giving a star at https://github.com/reloadware/reloadium
(5 + 9) = 14

process exited with exit code 0
```

**Desktop (please complete the following information):**
 - OS: Windows
 - OS version: 11
 - Reloadium package version: 0.9.4
 - PyCharm plugin version: 0.8.8
 - Editor: PyCharm 2022.2.3
 - Run mode: Run and Debug

**Comment by dkrystki** [comment]
Hi @nagataaaas 
You forgot to add a breakpoint

**Comment by nagataaaas** [comment]
Oh, I'm really sorry.
Now it works properly!
