### ISSUE TITLE
Pycharm plugin 0.9.4 not supported for Python 3.10.6

### ISSUE THREAD

**Issue by dirko** [reloadware/reloadium#57]
**Describe the bug**
I'm getting the `It seems like your platform or Python version are not supported yet.` message when running the PyCharm plugin.

**To Reproduce**
1. Click on the run or debug buttons.
2. See error

**Expected behavior**
Run.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS version: 11.5.2 (20G95)
 - Reloadium package version: 0.9.4
 - PyCharm plugin version: 0.8.8
 - Editor:  PyCharm 2022.2.3 (Professional Edition) Build #PY-222.4345.23
 - Run mode: Either Run or Debug

**Additional context**
Running from the command line seems fine.

**Comment by dkrystki** [comment]
Hey @dirko , thanks for submitting this. 
Reloadium plugin installs reloadium package to `<home>/.reloadium/package` directory, could you verify whether this directory exists and contains a package for the python version you are using?
If not could you please reinstall the plugin and submit the idea.log file?

If the package is correctly installed could you go to `<home>/.reloadium/package/<python version>/reloadium` and add the following lines at the beginning of the `__init__.py` file?
```
import sys
print(sys.path)
```
Then run your script using the Reloadium plugin and paste the output here?

**Comment by dkrystki** [comment]
@dirko 
Is it an M1 machine?

**Comment by dirko** [comment]
No, that is the strange part: `Processor: 2.3 GHz Quad-Core Intel Core i5`.

**Comment by dkrystki** [comment]
@dirko 
I might be onto something. Does this directory exist on your computer `/usr/libexec/rosetta/` 
I know you're not an M1 user but existence of this directory would explain this behavior since this is how currently the M1 machines are identified in the code.

**Comment by dirko** [comment]
Yes it exists, contains `debugserver      oahd             oahd-helper      oahd-root-helper runtime          runtime_t8027    translate_tool`. I'm unsure why I have it installed, I can't remember specifically installing it -- seems to be from Jan 1 2020.

**Comment by dkrystki** [comment]
I didn't expect rosetta to be installed on non M1 machines.
I'll try fixing that in the next release.

Until then to make it work:
1) Uninstall reloadium plugin
2) Remove `~/.reloadium/package`
3) Remove `/usr/libexec/rosetta/`
4) Install reloadium plugin

**Comment by dirko** [comment]
Great thanks! I'm unable to remove the directory (even with sudo), so will wait for a new version of the package. Looking forward to it, this plugin looks like a great tool.

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.5 and PyCharm plugin 0.9.0
