### ISSUE TITLE
Not working with Python 32 bit (x86)

### ISSUE THREAD

**Issue by nstefi** [reloadware/reloadium#65]
**Describe the bug**
I installed the Reloadium plugin version 0.8.8, then tried to debug my code, and I got an error:
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.

**To Reproduce**
1. Installed lates plugin (0.8.8) from this URL:
https://plugins.jetbrains.com/plugin/18509-reloadium--hot-reloading--profiling-for-python/versions
(File > Settings > Plugins - clicked the cogwheel icon and chose Install plugin from disk, installed from downloaded zip file)
2. Run or debug code with the orange icons
3. See error

**Expected behavior**
Debug without error

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit (running on a VM on Hyper-V)
 - OS version: 10.0.19044.2251
 - Reloadium package version: 0.9.4
 - PyCharm plugin version: 0.8.8
 - Editor: PyCharm 2022.02.03
 - Run mode: Either Run or Debug

**Additional context**
I didn't understand, do we need to install both the Reloadium package and the Reloadium plugin for PyCharm too?
I thought I would just install the plugin and it would work. But I have installed the package too via pip, using this command below, and it's still not working:
`pip install reloadium`

**Comment by dkrystki** [comment]
Reloadium package is bundled with the plugin so it should work out of the box.

Could you run it again with `RW_DEBUG` = `True` environmental variable on and paste the error?

**Comment by nstefi** [comment]
Hi Damian,
I did that and here is the error:
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\SNAGY.SCMAO\.reloadium\package\3.8\reloadium\__init__.py", line 4, in <module>
    pre_import_check()
  File "C:\Users\SNAGY.SCMAO\.reloadium\package\3.8\reloadium\__utils__.py", line 20, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'

**Comment by dkrystki** [comment]
Hey I just noticed you're using python 32 bit which is not supported anymore.
Please use 64 bit if possible.

**Comment by nstefi** [comment]
OK, I have installed the latest Python, version 3.11 (64 bit), and I get a very similar error:

It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\SNAGY.SCMAO\.reloadium\package\3.7\reloadium\__init__.py", line 4, in <module>
    pre_import_check()
  File "C:\Users\SNAGY.SCMAO\.reloadium\package\3.7\reloadium\__utils__.py", line 20, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'
