### ISSUE TITLE
PYTHONPATH didn't take into account by the plugin

### ISSUE THREAD

**Issue by tamzaselma** [reloadware/reloadium#66]
I have in my PYTHONPATH a folder containing several lib that I use in different python project.
When I run my script without Reloadium every thing is fine.
But with Reloadium I have : 

**Traceback (most recent call last):
  File "C:\Users\stamza\PyCharmProjectLocal\Support\Ioda-MedEco\Ioda_test.py", line 1, in <module>
    import ioda
ModuleNotFoundError: No module named 'ioda'**

**Comment by dkrystki** [comment]
Hi @tamzaselma 
Could you add this code before you import `ioda` module and post the output when running with Reloadium?
```
import sys
print(sys.path)
```

**Comment by dkrystki** [comment]
Also how do you set your `PYTHONPATH` env variable? Is it system wise or set in PyCharm?

**Comment by tamzaselma** [comment]
Thanks for you quick response @dkrystki,

Actually it's set in my system variable.

os.getenv('PYTHONPATH') --> C:\Users\stamza\.reloadium\package\3.8;C:\Users\stamza\PyCharmProjectLocal\Support

print(sys.path) ---> ['C:\\Users\\stamza\\PyCharmProjectLocal\\Support\\Ioda-MedEco', 'C:\\Users\\stamza\\PyCharmProjectLocal\\Support\\Ioda-MedEco', 'C:\\Users\\stamza\\.reloadium\\package\\3.8', 'C:\\Users\\stamza\\PyCharmProjectLocal\\Support', 'C:\\Program Files\\Python38\\python38.zip', 'C:\\Program Files\\Python38\\DLLs', 'C:\\Program Files\\Python38\\lib', 'C:\\Program Files\\Python38', 'C:\\Users\\stamza\\Venvs\\Support', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\win32', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\win32\\lib', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\Pythonwin']

Without Reloadium :
os.getenv('PYTHONPATH') --> C:\Users\stamza\PyCharmProjectLocal\Support;C:\Program Files\Python38;N:\MEDISSYS.32;N:\BBQIODA.32

print(sys.path) ---> ['C:\\Users\\stamza\\PyCharmProjectLocal\\Support\\Ioda-MedEco', 'C:\\Users\\stamza\\PyCharmProjectLocal\\Support', 'C:\\Program Files\\Python38', 'N:\\MEDISSYS.32', 'N:\\BBQIODA.32', 'C:\\Program Files\\Python38\\python38.zip', 'C:\\Program Files\\Python38\\DLLs', 'C:\\Program Files\\Python38\\lib', 'C:\\Users\\stamza\\Venvs\\Support', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\win32', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\win32\\lib', 'C:\\Users\\stamza\\Venvs\\Support\\lib\\site-packages\\Pythonwin']

**Comment by tamzaselma** [comment]
I try that  : 

os.environ['PYTHONPATH'] = os.getenv('PYTHONPATH') + ';Files\Python38;N:\MEDISSYS.32;N:\BBQIODA.32'

but have the same error :(

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.5 and PyCharm plugin 0.9.0
