### ISSUE TITLE
Mac 13 M1 and reloadium 9.0 installs x64 version

### ISSUE THREAD

**Issue by siilats** [reloadware/reloadium#67]
`file ~/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so`
~/.reloadium/package/3.10/reloadium/corium.cpython-310-darwin.so: Mach-O 64-bit dynamically linked shared library x86_64
`file ~/Downloads/reloadium4/lib/reloadium-0.9.0/META-INF/wheels/reloadium-0.9.5-cp310-cp310-macosx_12_0_arm64/reloadium/corium.cpython-310-darwin.so`
~/Downloads/reloadium4/lib/reloadium-0.9.0/META-INF/wheels/reloadium-0.9.5-cp310-cp310-macosx_12_0_arm64/reloadium/corium.cpython-310-darwin.so: Mach-O 64-bit dynamically linked shared library arm64

I tried to manually install with
`pip install ~/Downloads/reloadium/lib/reloadium-0.9.0/META-INF/wheels/reloadium-0.9.5-cp310-cp310-macosx_12_0_arm64.whl`

**Comment by siilats** [comment]
Manually copying the folder works, now there is a brand new error
`Unable to load extension pydevd_plugins.extensions.types.pydevd_plugin_pandas_types`
Similar to 
https://github.com/microsoft/vscode-jupyter/issues/10057 but reloadium seems to work

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.6 and PyCharm plugin 0.9.1
