### ISSUE TITLE
remote interpreter hangs on kill command (red square), and shows no profile information

### ISSUE THREAD

**Issue by noamzilo** [reloadware/reloadium#72]
**Describe the bug**
When running the plugin locally, (Windows) everything is fine.
When running using remote interpreter (on a remote Ubuntu), no profile information is displayed.

**To Reproduce**
Create a [remote interpreter configuration ](https://www.jetbrains.com/help/pycharm/configuring-remote-interpreters-via-ssh.html)
Debug using the plugin
See no profiling info

Also killing the (remote) debugger hangs if started from the plugin, which doesn't happen with regular debug.

**Expected behavior**
1. Ability to kill the remote interpreter
2. Ability to see profiling information.

**Screenshots**
![image](https://user-images.githubusercontent.com/4740186/203555480-2e9ebecc-3e37-446a-a375-2b5fc3cf2fce.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS version: [10]
 - M1 chip: [yes/no] don't know
 - Reloadium package version: 0.9.5
 - PyCharm plugin version: [e.g 0.8.0 or None] 0.9
 - Editor: [e.g PyCharm] Pycharm
 - Python Version: [eg. 3.9] 3.8.10
 - Python Architecture: [eg. 32bit, 64bit]64
 - Run mode: [e.g Run/Debug] Debug

**Comment by noamzilo** [comment]
I would like to start using this anyway, and would like a workaround suggestion if possible.
I am assuming the profile information is not shown because it is somehow saved locally, on the remote machine, and thus cannot be displayed on the local Pycharm host.

If that is the case, please let me know which are the relevant files, and I will make some ad-hoc ssh-tunnel to reflect them to the localhost

**Comment by dkrystki** [comment]
Hi @noamzilo 
You have to set path mappings for remote interpreters to work with reloadium.
I'm working on a warning dialog for that so it's more clear in the future.

**Comment by noamzilo** [comment]
Great to know it is supported after all. Which paths should I set?

**Comment by dkrystki** [comment]
The paths you will be using for hot reloading. The best is to add the project root directory which will cover everything.

**Comment by noamzilo** [comment]
I have added the root directory, which did not do the trick. 
Could you please specify which paths exactly need to be configured from Linux to Windows for hot reloading?

**Comment by dkrystki** [comment]
Can you confirm that you set the **project** root directory not system root directory?

Remote development using windows host and linux remote is supported https://github.com/reloadware/reloadium/issues/64

**Comment by dkrystki** [comment]
Closing due inactivity.
