### ISSUE TITLE
Reloadium experienced an error

### ISSUE THREAD

**Issue by oosd1** [reloadware/reloadium#73]
Hello, sir, the following is the example I ran with you,：

![image](https://user-images.githubusercontent.com/101701023/204199922-46d8e4bb-ca09-44aa-8359-671cf759ab16.png)

but when I changed the net parameter value and pressed ctrl+s to save, it gave the following error message:
![image](https://user-images.githubusercontent.com/101701023/204199985-201a1bcd-2d92-4b69-a06a-ad3c2b9fdaa2.png)

I don't know how to solve this problem, so I come to ask you for advice.

**Comment by dkrystki** [comment]
Hi @oosd1 
Thanks for submitting this.
Do you have any non ascii characters in your filename?

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.6 and PyCharm plugin 0.9.1
