### ISSUE TITLE
Pycharm plugin 0.9.0 not support for Python 3.10.6 On M2

### ISSUE THREAD

**Issue by endimirion** [reloadware/reloadium#74]
**Describe the bug**
When I run the orange button, occurs error:
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS version: 12.5.1
 - M1 chip: M2
 - Reloadium package version: None
 - PyCharm plugin version: 0.9.0
 - Editor: pycharm
 - Python Version: 3.10.6

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.6 and PyCharm plugin 0.9.1
