### ISSUE TITLE
Python version are not supported (3.10.7) on Windows

### ISSUE THREAD

**Issue by joszko** [reloadware/reloadium#78]
## Describe the bug*
Similar issue to #42 and #57 but on Windows 10. Plugin stopped working claiming `It seems like your platform or Python version are not supported yet.` I'm using Pycharm Community 2022.3 and Virtualenv with Python 3.10.7.

Tried uninstalling plugin, deleting `.reloadium` directory and installing again as recommended in other issues but with no success.

Running with RW_DEBUG=True returns the following:

`Traceback (most recent call last):
  File "C:\Users\8008701\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\8008701\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\8008701\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\8008701\.reloadium\package\3.7\reloadium\__init__.py", line 4, in <module>
    pre_import_check()
  File "C:\Users\8008701\.reloadium\package\3.7\reloadium\__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'
`

## To Reproduce
NA

## Expected behavior
Plugin should work

## Screenshots
INA

## Desktop (please complete the following information):**
 - OS: Windows
 - OS version: 10
 - M1 chip: [yes/no] no
 - Reloadium package version: 0.9.6
 - PyCharm plugin version: 0.9.1
 - Editor: PyCharm Community 2022.3
 - Python Version: 3.10.7
 - Python Architecture: 64bit
 - Run mode: Run/Debug

## Additional context
I have multiple versions of Python installed (2.7, 3.7, 3.8 and 3.10) but Virtualenv is using 3.10.7

**Comment by dkrystki** [comment]
Hey @joszko thanks for submitting this.

So it was working before?
What has changed? 
Did you upgrade PyCharm version by any chance?

The plugin determines which version to load by using version provided by the interpreter settings. I can see it's trying to load version for 3.7 which is incorrect.

Could you try recreating your interpreter?

**Comment by joszko** [comment]
After creating new environment it started working again.

Thanks
