### ISSUE TITLE
Not working on Python 3.9.15

### ISSUE THREAD

**Issue by daneren** [reloadware/reloadium#81]
## Describe the bug*
Not working on Python 3.9.15.

## To Reproduce

<img width="796" alt="image" src="https://user-images.githubusercontent.com/13315266/210738726-c2e0a8d1-9ede-4247-bab7-8f468a5b9141.png">

<img width="435" alt="image" src="https://user-images.githubusercontent.com/13315266/210740082-6edda287-3683-46bb-a1d0-fd54a3f55516.png">

## Desktop (please complete the following information):**
 - OS: macOS 
 - OS version: 11.5.2
 - Reloadium package version: 0.9.6
 - PyCharm plugin version: 0.9.1
 - Editor: PyCharm
 - Python Version: 3.9.15
 - Python Architecture: 64bit
 - Run mode: Run and Debug

**Comment by dkrystki** [comment]
Thanks for submitting this.
Could you run it with `RW_DEBUG` environmental variable set to `True` and paste the stack trace?

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.7 and PyCharm plugin 0.9.2
