### ISSUE TITLE
"SyntaxError: 'return' with value in async generator" when using async context managers

### ISSUE THREAD

**Issue by LilSpazJoekp** [reloadware/reloadium#85]
## Describe the bug*
Reloadium crashes when using async context managers.

## To Reproduce
1. Run this code in debug mode:
   ```py
   import asyncio
   from contextlib import asynccontextmanager
 
 
   @asynccontextmanager
   async def async_context_manager():
       print("entered async context manager")
       test_value = 1
       yield test_value
       print("exiting async context manager")
 
 
   async def async_main():
       print("getting ready to enter async context manager")
       async with async_context_manager() as manager:
           print(manager)
       print("exited async context manager")
 
 
   if __name__ == "__main__":
       asyncio.run(async_main())
   ```

## Expected behavior
No syntax error.

## Screenshots
<img width="831" alt="image" src="https://user-images.githubusercontent.com/15524072/213927505-e6146194-02fe-403d-9d6b-ae88bdd780c7.png">

## Desktop or remote (please complete the following information):**
 - OS: macOS 
 - OS version: macOS Monterey 12.4
 - M1 chip: no
 - Reloadium package version: 0.9.7
 - PyCharm plugin version: 0.9.2
 - Editor: PyCharm
 - Python Version: Python 3.10.0
 - Python Architecture: 64bit, 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)]
 - Run mode: Debug

## Additional context
If I remove the `asynccontextmanager` decorator, it does not crash, however the code does not work the way I'd like. This seems to be an error with reloadium because running without it, my code works as expected:

```shell
❯ python main.py                                                                                                                                                                                                 
getting ready to enter async context manager
entered async context manager
1
exiting async context manager
exited async context manager
```

 I would help debug reloadium and find a root cause but it seems corium is obfuscated.

**Comment by dkrystki** [comment]
Fixed in reloadium 0.9.9 and PyCharm plugin 0.9.4
