### ISSUE TITLE
MacOS M1, Python 3.9: fails as unsupported

### ISSUE THREAD

**Issue by Tradunsky** [reloadware/reloadium#86]
## Describe the bug*
```
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python >= 3.7 (3.9 for M1) are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
```

## To Reproduce
1. Click on Debug of python configuration for test run

## Expected behavior
Should work?

## Desktop or remote (please complete the following information):**
 - OS: MacOS
 - OS version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
 - M1 chip: yes
 - PyCharm plugin version: 0.8.11
 - Editor: Build #PY-223.8214.51, built on December 20, 2022
 - Python Version: Python 3.9.16 (main, Jan 12 2023, 23:52:36)  [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
 - Python Architecture: x86_64
 - Run mode: Debug

## Additional context
Just noticed I actually installed https://plugins.jetbrains.com/plugin/20302-you-com-with-reloadium--hot-reloading--profiling-for-python, not clear https://plugins.jetbrains.com/plugin/18509-reloadium--hot-reloading--profiling-for-python if it matters.

**Comment by dkrystki** [comment]
Please install https://plugins.jetbrains.com/plugin/18509-reloadium--hot-reloading--profiling-for-python `You.com with reloadium` is a fork which is not maintained by me.
