### ISSUE TITLE
ModuleNotFoundError - Linux Python 3.10

### ISSUE THREAD

**Issue by rafa761** [reloadware/reloadium#90]
## Describe the bug*
When I try to run a project with reloadium on linux using python 3.10, I'm getting error "ModuleNotFoundError: No module named 'reloadium.corium'"

Already uninstalled plugin and deleted ".reloadium" directory, but got same error

## To Reproduce
1. Open Pycharm
2. Run a python configuration to start the project

## Expected behavior
Run code with reloadium

## Screenshots
![image](https://user-images.githubusercontent.com/41598843/215140906-f761bab6-105c-40d8-a1f2-af8617d857dd.png)

## Desktop or remote (please complete the following information):**
 - OS: Linux PopOs
 - OS version: 22.04
 - M1 chip: no
 - Reloadium package version: 0.9.10
 - PyCharm plugin version: 0.9.5
 - Editor: PyCharm 2022.3.2 (Professional Edition)
 - Python Version: 3.10.6
 - Python Architecture: 64bit
 - Run mode: Run or Debug

## Additional context
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/rafael/.reloadium/package/3.7/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/home/rafael/.reloadium/package/3.7/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'

**Comment by ksengottuvel** [comment]
I encountered a similar issue. I'm using pyenv to manage python versions between projects. It tries to import a package for python3.7. Am I missing any configuration to pin the python version?

```
/home/vel/.pyenv/versions/py39_venv/bin/python -m reloadium pydev_proxy /home/vel/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8214.51/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 37743 --file /home/vel/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.8214.51/plugins/python/helpers/pycharm/_jb_pytest_runner.py --target test_entity_delivered_notification.py::SendDeliveryNotificationTest 
Testing started at 11:03 pm ...
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "/home/vel/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/vel/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/vel/.pyenv/versions/3.9.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/vel/.reloadium/package/3.7/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/home/vel/.reloadium/package/3.7/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'

Process finished with exit code 1
```

**Comment by sebastiaopf** [comment]
I have the same issue with Linux Mint, PyCharm and Python 3.9:

OS: Linux Mint
OS version: 19.3
M1 chip: no
Reloadium package version: 0.9.7
PyCharm plugin version: 0.9.5
Editor: PyCharm 2022.3.2 (Professional Edition)
Python Version: 3.9.16
Python Architecture: 64bit
Run mode: Run or Debug

(...)/source/apollo/venv/bin/python -m reloadium pydev_proxy /opt/jetbrains/pycharm/pycharm-2022.1.3/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 45085 --file (...)/manage.py runserver 8000 
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "(...)/.reloadium/package/3.7/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "(...)/.reloadium/package/3.7/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'

Process finished with exit code 1

**Comment by dkrystki** [comment]
I believe it's related to https://github.com/reloadware/reloadium/issues/78
Could you guys try recreating your interpreter configuration?

**Comment by sebastiaopf** [comment]
> I believe it's related to #78 Could you guys try recreating your interpreter configuration?

You are right. Creating new interpreter settings for the project (and associating the new interpreter with the configuration I want to run), with a new virtual environment in PyCharm fixes the problem. Now it's running the application through the plugin on PyCharm.

Thank you very much.

**Comment by rafa761** [comment]
It worked recreating the interpreter.
