### ISSUE TITLE
PyCharm: New UI support

### ISSUE THREAD

**Issue by hhharsha36** [reloadware/reloadium#91]
Reloadium 'Run' and 'Debug' buttons are not visible when 'New UI' option is enabled in 'PyCharm'

## To Reproduce
1. Go to 'Settings -> Appearance & Behavior -> New UI'
2. Check 'Enable new UI' box and restart the IDE
3. The reloadium 'run' and ' debug' buttons are absent beside the normal run button

## Expected behavior
Reloadium 'Run' and 'Debug' buttons should co-exist with the normal run button when 'New UI' option is enabled

## Screenshots
![Screenshot (34)](https://user-images.githubusercontent.com/28597188/215259468-62b81206-22b0-4eac-ac93-7de2d7ba66f8.png)

## Desktop or remote (please complete the following information):**
 - OS: Windows
 - OS version: 22H2
 - Reloadium package version: 0.9.5
 - PyCharm plugin version: 0.9.5
 - Editor: PyCharm
 - Python Version: 3.11
 - Python Architecture: 64bit
 - Run mode: Both

**Comment by ChillarAnand** [comment]
In the new UI, these buttons are present under the `old toolbar` as shown below.

<img width="1277" alt="Screenshot 2023-02-17 at 11 06 49" src="https://user-images.githubusercontent.com/4463796/219558490-1a461b82-de9d-4d0d-b050-8be34ffaa198.png">

<img width="1277" alt="Screenshot 2023-02-17 at 11 06 56" src="https://user-images.githubusercontent.com/4463796/219558500-1217f7d9-1f7c-4437-ab74-2f271411b784.png">

I don't know if PyCharm allows plugins to display custom buttons in the main tool bar in the new UI.

**Comment by dkrystki** [comment]
I managed to add them to the new UI in a similar way it is in the old one.
It's coming with the next release.

**Comment by dkrystki** [comment]
Added in PyCharm plugin 0.9.6
