### ISSUE TITLE
PyCharm with virtualenv and reloadium plugin does not work - No module named reloadium.corium

### ISSUE THREAD

**Issue by saphireee** [reloadware/reloadium#95]
PyCharm Pro 2022.3.1 with virtualenv and Python 3.10 after icon click "Debug 'dl' with Reloadium" debug console output:

/home/user/py310env/bin/python -m reloadium pydev_proxy /home/user/pycharm/plugins/python/helpers/pydev/pydevd.py --multiprocess --save-signatures --qt-support=auto --client 127.0.0.1 --port 41999 --file /home/user/XXX/yyy/dl.py 
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.10 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/.reloadium/package/3.7/reloadium/__init__.py", line 4, in <module>
    pre_import_check()
  File "/home/user/.reloadium/package/3.7/reloadium/__utils__.py", line 21, in pre_import_check
    import reloadium.corium
**ModuleNotFoundError: No module named 'reloadium.corium'**

Process finished with exit code 1

**Comment by dkrystki** [comment]
I believe it's related to this https://github.com/reloadware/reloadium/issues/90

**Comment by saphireee** [comment]
Yes, **recreating virtualenv environment after Reloadium plugin installation helps** so please put that info into documentation - it will spare You many new issues.

**Comment by onealj** [comment]
This procedure worked for me:

1. Install Reloadium
2. Run > Edit Configurations... > Environment variables > append ";RW_DEBUG=1"
3. Create new venv (based on python 3.10), source the venv if not automatically done by PyCharm
4. python.exe -m pip install --upgrade pip
5. pip install ipython reloadium
6. pip install --editable other packages your venv needs
7. Run reloadium debug on your script

**Comment by sisisiss** [comment]
C:\ProgramData\Anaconda3\python.exe -m reloadium_launcher pydev_proxy "C:/Program Files/JetBrains/PyCharm 2023.1.2/plugins/python/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 63148 --file D:\yuanma\vnpy\vnpy\run.py 
It seems like your platform or Python version are not supported yet.
Windows, Linux, macOS and Python 64 bit >= 3.7 (>= 3.9 for M1) <= 3.11 are currently supported.
Please submit a github issue if you believe Reloadium should be working on your system at
https://github.com/reloadware/reloadium
To see the exception run Reloadium with environmental variable RW_DEBUG=True
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\11236\.reloadium\package\reloadium_launcher.py", line 25, in <module>
    from reloadium.corium import start
  File "C:\ProgramData\Anaconda3\lib\site-packages\reloadium\__init__.py", line 4, in <module>
    pre_import_check()
  File "C:\ProgramData\Anaconda3\lib\site-packages\reloadium\__utils__.py", line 24, in pre_import_check
    import reloadium.corium
ModuleNotFoundError: No module named 'reloadium.corium'
same problem

**Comment by dkrystki** [comment]
@sisisiss Could you provide more information about your setup? Which Reloadium plugin version are you using? What python version?
Could you list contents of `<home>/.reloadium/package` directory?
