### ISSUE TITLE
Reloadium doesn't work on M1 mac with Python 3.9

### ISSUE THREAD

**Issue by ChillarAnand** [reloadware/reloadium#98]
## Describe the bug*

On some M1 macs, reloadium is working fine with Pyton 3.9. On few other macs, it is failing to run.

## To Reproduce

Not able to reproduce the bug on all M1 macs. 

## Expected behavior
Reloadium should run the application.

## Screenshots

<img width="1280" alt="Screenshot 2023-02-06 at 08 41 19" src="https://user-images.githubusercontent.com/4463796/216875865-f3b49259-5f70-4d67-a56f-90466ab9f44c.png">

## Desktop or remote (please complete the following information):**
 - OS: Mac
 - OS version: 13.0.1
 - M1 chip: yes
 - Reloadium package version: 0.9.10
 - PyCharm plugin version: 0.9.5
 - Editor: PyCharm
 - Python Version: 3.9.12
 - Python Architecture:64
 - Run mode: Debug

**Comment by dkrystki** [comment]
Are you sure this is the newest reloadium version?
By looking at the message it looks like it is not.

**Comment by ChillarAnand** [comment]
<img width="960" alt="Screenshot 2023-02-06 at 10 37 35" src="https://user-images.githubusercontent.com/118716023/216888340-6ead1440-019c-4ac0-b808-10d70a63f74b.png">

This is the latest version available on PyPi.

**Comment by dkrystki** [comment]
Can you got to `Reloadium`->`About` and see what versions are there?

**Comment by ChillarAnand** [comment]
<img width="573" alt="Screenshot 2023-02-06 at 11 31 47" src="https://user-images.githubusercontent.com/4463796/216895310-4146362e-1853-441c-aca8-38d6363b8b36.png">

**Comment by dkrystki** [comment]
Although looks correct the picked up package is wrong since the message should end up with `To see the exception run reloadium with environmental variable RW_DEBUG=True` which was added in the newer version.

Could you please uninstall the plugin, remove `~/.reloadium/package` directory, and install it again?

**Comment by ChillarAnand** [comment]
Deleted the virtualenv and plugin directory and created a fresh setup. It is working fine now. Thanks @dkrystki 

<img width="987" alt="Screenshot 2023-02-06 at 12 02 38" src="https://user-images.githubusercontent.com/4463796/216899750-64234bd8-aa08-490a-9d8b-4ac447a34812.png">

The following message is not yet shown though.

`To see the exception run reloadium with environmental variable RW_DEBUG=True`

**Comment by dkrystki** [comment]
That message is only shown when incompatible system is detected.
I'm glad it's working now!
